# Generated by Django 4.1.5 on 2023-01-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_store', '0003_rename_created_date_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'rating', 'verbose_name_plural': 'Rates'},
        ),
        migrations.AlterField(
            model_name='rating',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='rating',
            table='rate',
        ),
    ]
