# Generated by Django 4.1.5 on 2023-01-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_store', '0004_alter_rating_options_alter_rating_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
