# Generated by Django 4.1.5 on 2023-03-09 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_store', '0006_alter_rating_options_alter_rating_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'rating', 'verbose_name_plural': 'Rate and Review'},
        ),
    ]
