# Generated by Django 4.1.7 on 2023-11-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_store', '0011_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='vendor',
        ),
    ]
