# Generated by Django 4.1.5 on 2023-01-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_store', '0002_variation'),
        ('product_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='variation',
            field=models.ManyToManyField(blank=True, to='product_store.variation'),
        ),
    ]
