# Generated by Django 4.1.5 on 2023-01-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_cart', '0003_cartproduct_user_alter_cartproduct_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartproduct',
            table='cart_product',
        ),
    ]
